apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
- mongodb.yaml
- ingress.yml
images:
- name: sd0188-practical-devop-backend/backend-latest
  newTag: "backend-latest"
- name: sd0188-practical-devop-frontend/frontend-latest
  newTag: "frontend-latest"
